# Site settings
title: GDQ Stats
description: > # this means to ignore newlines until "baseurl:"
  Stats page for GDQ
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gdqstat.us" # the base hostname & protocol for your site

current_event: Awesome Games Done Quick
current_event_short_hand: AGDQ
current_event_year: 2017

# Build settings
markdown: kramdown

# Exclude
exclude: [LICENSE, README.md, Rakefile, Gemfile, Gemfile.lock, other_graphs.html]