# Site settings
title: GDQ Stats
description: >
  Live Data Visualizations for GamesDoneQuick Livestreams
author: Benjamin Congdon
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gdqstat.us" # the base hostname & protocol for your site
repository: bcongdon/gdq-stats

sass:
  sass_dir: _scss

current_event: Awesome Games Done Quick
current_event_short_hand: AGDQ
current_event_year: 2018

# Build settings
markdown: kramdown

# Exclude
exclude: [
  animals.html,
  bower.json,
  gdq-stats.sublime-project,
  gdq-stats.sublime-workspace,
  Gemfile,
  Gemfile.lock,
  LICENSE,
  node_modules,
  other_graphs.html,
  package-lock.js,
  package.json,
  Rakefile,
  README.md,
  vendor,
  js,
  webpack-stats.json,
  webpack.config.js,
  chat_stats.html,
  donations.html,
  games.html,
  graph.html,
  main.html
]

previous_events:
  - name: SGDQ
    year: 2017

  - name: AGDQ
    year: 2017

  - name: SGDQ
    year: 2016
