# Site settings
title: GDQ Stats
description: > # this means to ignore newlines until "baseurl:"
  Stats page for GDQ
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gdqstat.us" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Exclude
exclude: [LICENSE, README.md, Rakefile, Gemfile, Gemfile.lock]