# Site settings
title: GDQ Stats
description: >
  Live Data Visualizations for GamesDoneQuick Livestreams
author: Benjamin Congdon
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gdqstat.us" # the base hostname & protocol for your site

sass:
  sass_dir: _scss

current_event: Summer Games Done Quick
current_event_short_hand: SGDQ
current_event_year: 2017

# Build settings
markdown: kramdown

# Exclude
exclude: [LICENSE, README.md, Rakefile, Gemfile, Gemfile.lock, other_graphs.html,
          bower.json, node_modules, gdq-stats.sublime-project, webpack.config.js,
          package.json, package-lock.js, flipclock.html, webpack-stats.json]

previous_events:
  - name: AGDQ
    year: 2017

  - name: SGDQ
    year: 2016
