URL: "http://gdqstat.us"
title: GDQStat.us

author: Benjamin Congdon

googleAnalytics: UA-72102716-2

languageCode: "en-us"
languageLang: "en"

disableKinds: ["RSS", "taxonomy", "taxonomyTerm", "sitemap", "404"]

enableRobotsTXT: true

params:
  current_event: Summer Games Done Quick
  current_event_short_hand: SGDQ
  current_event_year: 2018

  # Set to "true" to disable home page and switch to flipclock as homepage
  countdown_enabled: true

  # The time that the flipclock counts down to
  event_start: "2018-06-24T08:30:00.00-08:00"

  previous_events:
    - name: AGDQ
      year: 2018

    - name: SGDQ
      year: 2017

    - name: AGDQ
      year: 2017

    - name: SGDQ
      year: 2016

  description: >
    Live Data Visualizations for GamesDoneQuick Livestreams