URL: "http://gdqstat.us"
title: GDQStat.us

author: Benjamin Congdon

googleAnalytics: UA-72102716-2

languageCode: "en-us"
languageLang: "en"

disableKinds: ["RSS", "taxonomy", "taxonomyTerm", "sitemap", "404"]

enableRobotsTXT: true

params:
  current_event: Summer Games Done Quick Online
  current_event_short_hand: SGDQ
  current_event_year: 2021

  # Set to "true" to disable home page and switch to flipclock as homepage
  countdown_enabled: true

  # The time that the flipclock counts down to
  event_start: "2021-07-04T09:00:00.00-07:00"

  previous_events:
    - name: AGDQ
      year: 2021

    - name: SGDQ
      year: 2020

    - name: AGDQ
      year: 2020

    - name: SGDQ
      year: 2019

    - name: AGDQ
      year: 2019

    - name: SGDQ
      year: 2018

    - name: AGDQ
      year: 2018

    - name: SGDQ
      year: 2017

    - name: AGDQ
      year: 2017

    - name: SGDQ
      year: 2016

  description: >
    Data Visualizations for GamesDoneQuick Marathons
